version: "3"
services:
    reverseproxy:
        image: thismycatsdockerhub/reverseproxy
        ports:
            - 8080:8080
        restart: always
        depends_on:
            - api-user
            - api-feed  
    api-user:
        image: thismycatsdockerhub/udagram-api-user
        env_file: 
            - envfordocker.env
    api-feed:
        image: thismycatsdockerhub/udagram-api-feed
        env_file: 
            - envfordocker.env
    frontend:
        image: thismycatsdockerhub/udagram-frontend
      
